- README.rst
> Change status image

- README.rst
- appveyor.yml
- tests/test_config.py
- tests/test_handler.py
- tests/test_robot.py
- tests/test_session.py
> Add AppVeyor CI

- appveyor.yml
- dev-requirements.txt
- travis/install.sh
- travis/script.sh
- werobot/crypto/__init__.py
> Replace Pycrypto with Cryptography

- werobot/robot.py
wsgi属性没有return
361行拼写错误from werobot.contrib.bottle import make_view
> 开发版本robot.py错误

- .travis.yml
- docs/config.rst
- docs/index.rst
- werobot/config.py
- werobot/robot.py
> Config docs

- .travis.yml
- appveyor.yml
- dev-requirements.txt
- tox-requirements.txt
- travis/install.sh
- travis/script.sh
- Use cryptography 1.7.1 to avoid Illegal instruction error
- Fix travis error on macOS 10.12
- disallow failure on macOS 10.12
- Run most builds on macOS 10.12
> Fix Travis

- docs/changelog.rst
- docs/session.rst
- docs/start.rst
- werobot/robot.py
- werobot/utils.py
> Lazy init session storage and deprecate enable_session

- MANIFEST.in
- docs/changelog.rst
> Fix missing error page file

- docs/changelog.rst
- docs/config.rst
- tests/test_robot.py
- werobot/robot.py
> Allow pass `config` param in BaseRoBot init

- docs/changelog.rst
- docs/handlers.rst
- tests/test_robot.py
- tests/test_utils.py
- werobot/robot.py
- werobot/utils.py
> add add_filter

- docs/changelog.rst
- setup.cfg
- tests/test_utils.py
- werobot/session/sqlitestorage.py
- werobot/utils.py
> Use secrets.choice for generate_token

- docs/client.rst
> Add docs for 48001 error

- docs/replies.rst
> fix typo in replies.rst #210

- travis/script.sh
> Run `brew services list` before travis/script.sh

- werobot/robot.py
> Use dict comprehension inside robot._handlers.

- docs/changelog.rst
> add changelog

- docs/changelog.rst
- tests/test_handler.py
- tests/test_robot.py
- werobot/robot.py
> 添加了 video & short video 修饰器

- tox-win.ini
- tox.ini
> add test for django 1.11

- docs/encryption.rst
- werobot/crypto/__init__.py
> update encryption doc

- docs/changelog.rst
- docs/contrib.rst
- tests/test_contrib.py
- tests/test_replies.py
- tests/test_robot.py
- tox-win.ini
- tox.ini
- werobot/client.py
https://www.djangoproject.com/download/#supported-versions
> drop support for Django < 1.8

- tox-win.ini
- tox.ini
https://www.djangoproject.com/download/#supported-versions
> Drop tests for Django1.9

- tests/test_client.py
- werobot/session/filestorage.py
- werobot/session/saekvstorage.py
> More tests

- docs/changelog.rst
- tox-win.ini
- tox.ini
> run tests for django 2.0

- docs/contrib.rst
> contrib docs: change instance name to `myrobot`

- .travis.yml
> move macOS image to 8.3

- docs/deploy.rst
> docs(deploy): update supervisor config example

- docs/handlers.rst
> docs(handler): add doc for card handler

- README.rst
.. and remove instructions for installing pip because it's too basic and (sort of) outdated
> docs(README): update semaphore ci badge

- README.rst
> docs(README): remove session

- .github/issue-close-bot.yml
> chore(bot): add issue bot config

- docs/handlers.rst
- tests/test_robot.py
- werobot/robot.py
以方便在如下场景实现功能
```python
@robot.filter(re.compile("bb(.*)"))
def b(message,session,match):
return match.group(1)
```
> 使正则匹配到的对象传入处理函数

- appveyor.yml
- tests/test_session.py
- tox-requirements.txt
- travis/install.sh
> 在测试 Session 部分使用 Mock

- tests/test_client.py
- werobot/client.py
> feat(client): add sending miniprogrampage custom message #298

- dev-requirements.txt
- tox-requirements.txt
> build: pin dependencies

- .travis.yml
https://www.travisbuddy.com/getting-started
> ci(travis): add travisbuddy

- .circleci/config.yml
- README.rst
> ci(circleci): add circleci support #293

- README.rst
> docs(readme): change the badge for circleci

- .circleci/config.yml
> ci(circleci): remove db images

- .circleci/config.yml
- .travis.yml
- tox-requirements.txt
- tox-win.ini
- tox.ini
>  build(python): add support for python 3.7

- .circleci/config.yml
- tox-requirements.txt
- tox-win.ini
> ci(circle): add docs test and lint

- werobot/messages/events.py
> style(message): fix style error due to new version yapf

- docs/replies.rst
更新了 article reply 部分的文档
**参考**: https://mp.weixin.qq.com/cgi-bin/announce?action=getannouncement&announce_id=115383153198yAvN&lang=zh_CN
> docs(reply): update article reply doc

- docs/changelog.rst
- tests/test_client.py
- werobot/client.py
>  feat(client): add kf_account as arg to client message related api

- tox-requirements.txt
> test: upgrade mongomock

- tests/test_session.py
- werobot/session/postgresqlstorage.py
> PostgreSQLStorage for Session

- docs/api.rst
- docs/changelog.rst
> docs: add changelog for 1.8.0 and missing docs for postgresql storage

- tox-requirements.txt
> chore(dependencies): freeze tornado version to 5.1.1

- tests/django_test_env/django_test/urls.py
- tests/test_contrib.py
- tox-requirements.txt
> tests: adapt to Tornado 6.0.0+

- README.rst
> docs(readme): remove slack badge

- appveyor.yml
> ci(appveyor): force reinstall when install tox

- .vscode/settings.json
- tests/test_contrib.py
> test: test tornado via WSGIAdapter for tornado < 6

- docs/handlers.rst
> docs(handlers): fix typo

- .bumpversion.cfg
- docs/changelog.rst
- docs/client.rst
- werobot/__init__.py
- werobot/client.py
> chore(release): version 1.10.0

- .travis.yml
- tests/test_client.py
> Fix Travis CI

- docs/changelog.rst
- docs/contrib.rst
- tox.ini
> test: remove testing outdated Django versions
